# Generated by Django 6.0 on 2025-12-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_document_is_processed_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chunks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='confidence_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
