# Generated by Django 6.0 on 2026-01-03 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_appconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedTable',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('doc_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(db_index=True, max_length=500)),
                ('page', models.IntegerField()),
                ('table_index', models.IntegerField()),
                ('headers', models.JSONField(blank=True, default=list)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('table_data', models.JSONField()),
                ('table_type', models.CharField(choices=[('key_value', 'Key-Value Table'), ('single_row', 'Single Row Table'), ('single_cell', 'Single Cell Table'), ('multi_row', 'Multi-Row Table')], db_index=True, max_length=20)),
                ('searchable_text', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inherited_tables', to='process.thread')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='process.thread')),
            ],
            options={
                'ordering': ['doc_id', 'page', 'table_index'],
                'indexes': [models.Index(fields=['thread', 'table_type'], name='process_ext_thread__cebe4c_idx'), models.Index(fields=['source', 'page'], name='process_ext_source_5398b8_idx'), models.Index(fields=['doc_id', 'page'], name='process_ext_doc_id_d31b77_idx')],
            },
        ),
    ]
