# Generated by Django 6.0 on 2026-01-03 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_extractedtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedtable',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='extractedtable',
            name='table_data',
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('is_header', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='process.extractedtable')),
            ],
            options={
                'ordering': ['table', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='TableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_index', models.IntegerField()),
                ('column_name', models.CharField(blank=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('is_key', models.BooleanField(db_index=True, default=False)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='process.tablerow')),
            ],
            options={
                'ordering': ['row', 'column_index'],
            },
        ),
        migrations.AddIndex(
            model_name='tablerow',
            index=models.Index(fields=['table', 'row_index'], name='process_tab_table_i_b0d14e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablerow',
            unique_together={('table', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='tablecell',
            index=models.Index(fields=['row', 'column_index'], name='process_tab_row_id_ee4761_idx'),
        ),
        migrations.AddIndex(
            model_name='tablecell',
            index=models.Index(fields=['is_key', 'value'], name='process_tab_is_key_d994e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tablecell',
            unique_together={('row', 'column_index')},
        ),
    ]
