# Generated by Django 6.0 on 2026-02-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_remove_extractedtable_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('mrls', 'MRLS - Maintenance Repair Level Schedule'), ('ispl', 'ISPL - Illustrated Spare Parts List'), ('manual', 'Manual - User/Technical Manual'), ('catalog', 'Catalog - Parts Catalog'), ('specification', 'Specification - Technical Specs'), ('drawing', 'Drawing - Engineering Drawing'), ('other', 'Other - General Document')], default='other', max_length=50),
        ),
    ]
