# Generated by Django 6.0 on 2026-02-11 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='process.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='revision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
