# Generated by Django 6.0 on 2026-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_document_notes_document_previous_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtable',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
