# Generated by Django 6.0 on 2026-08-17 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_add_ingestion_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_a', models.CharField(db_index=True, max_length=500)),
                ('source_b', models.CharField(db_index=True, max_length=500)),
                ('column_key', models.CharField(db_index=True, max_length=255)),
                ('value_a', models.CharField(max_length=255)),
                ('value_b', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.thread')),
            ],
            options={
                'indexes': [models.Index(fields=['source_a', 'source_b', 'column_key'], name='process_con_source__c32696_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_a', 'source_b', 'column_key', 'value_a', 'value_b'), name='unique_confirmed_match')],
            },
        ),
    ]
