# Generated by Django 6.0 on 2026-08-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_confirmedmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=255)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('parent_thread_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source', models.CharField(db_index=True, max_length=500)),
                ('page', models.IntegerField(default=1)),
                ('kind', models.CharField(choices=[('text', 'Prose / paragraph text'), ('table', 'Table cell text')], default='text', max_length=10)),
                ('text_norm', models.TextField(blank=True, default='')),
                ('text_nospace', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['doc_id', 'page'], name='process_doc_doc_id_e19842_idx')],
                'constraints': [models.UniqueConstraint(fields=('doc_id', 'page', 'kind'), name='unique_page_text_per_doc')],
            },
        ),
        migrations.CreateModel(
            name='IdentifierMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=255)),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('parent_thread_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source', models.CharField(db_index=True, max_length=500)),
                ('value_norm', models.CharField(db_index=True, max_length=255)),
                ('value_nospace', models.CharField(db_index=True, max_length=255)),
                ('value_raw', models.CharField(blank=True, default='', max_length=255)),
                ('page', models.IntegerField(default=1)),
                ('kind', models.CharField(choices=[('text', 'Prose / paragraph text'), ('table', 'Table cell text')], default='text', max_length=10)),
                ('occurrences', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['doc_id', 'value_norm'], name='process_ide_doc_id_b6b28b_idx'), models.Index(fields=['value_norm'], name='process_ide_value_n_861c29_idx'), models.Index(fields=['doc_id', 'value_nospace'], name='process_ide_doc_id_8f5ab9_idx')],
                'constraints': [models.UniqueConstraint(fields=('doc_id', 'value_norm', 'page', 'kind'), name='unique_mention_per_doc_page')],
            },
        ),
    ]
