# Generated by Django 6.0 on 2026-08-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_documentpagetext_identifiermention'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=500)),
                ('thread_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('field', models.CharField(db_index=True, max_length=64)),
                ('header_text', models.CharField(max_length=500)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doc_id', 'field'), name='unique_column_role_per_doc')],
            },
        ),
    ]
