# Generated by Django 6.0 on 2026-08-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_columnrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extraction_stats',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
