"""
Django settings for ragocr project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-_d0f!i*$#4%-+25(6yw$#-y-9v&i@25l(-s66j04gcxzkw$9!o')

DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# When running as the standalone Electron app (RAGOCR_DATA_DIR set), write Django
# logs + the actual exception traceback to a file in the data directory. Without
# this the .exe runs windowless and Django stack traces vanish into stdout.
if os.environ.get('RAGOCR_DATA_DIR'):
    _log_dir = Path(os.environ['RAGOCR_DATA_DIR']) / 'logs'
    _log_dir.mkdir(parents=True, exist_ok=True)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{asctime} [{levelname}] {name}: {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': str(_log_dir / 'ragocr.log'),
                'maxBytes': 5 * 1024 * 1024,
                'backupCount': 3,
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {'handlers': ['file'], 'level': 'INFO', 'propagate': False},
            'django.request': {'handlers': ['file'], 'level': 'ERROR', 'propagate': False},
            'process': {'handlers': ['file'], 'level': 'DEBUG', 'propagate': False},
        },
    }

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'process',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ragocr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ragocr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Per-user writable data dir. The Electron standalone launcher sets RAGOCR_DATA_DIR;
# otherwise we fall back to BASE_DIR (dev mode).
_data_dir = os.environ.get('RAGOCR_DATA_DIR')
if _data_dir:
    DATA_DIR = Path(_data_dir)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
else:
    DATA_DIR = BASE_DIR

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_URL = '/static/'

# Frontend build directory (Vite output). Used by the standalone Electron build.
# Two layouts supported:
#   dev / source repo:   <repo>/frontend/dist/
#   standalone runtime:  <runtime>/frontend/    (flat — provisioning copies dist contents here)
# RAGOCR_FRONTEND_DIR env var overrides both if set.
_frontend_env = os.environ.get('RAGOCR_FRONTEND_DIR')
if _frontend_env:
    FRONTEND_DIST_DIR = Path(_frontend_env).resolve()
else:
    _candidates = [
        (BASE_DIR / ".." / "frontend" / "dist").resolve(),
        (BASE_DIR / ".." / "frontend").resolve(),
    ]
    FRONTEND_DIST_DIR = next((c for c in _candidates if (c / "index.html").is_file()), _candidates[0])

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Serve Vite-built assets (the JS/CSS bundles) when the directory exists.
if (FRONTEND_DIST_DIR / "assets").is_dir():
    STATICFILES_DIRS.append(FRONTEND_DIST_DIR / "assets")

STATIC_ROOT = BASE_DIR / "staticfiles"

# CORS Settings (for React frontend)
_cors_origins = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:80,http://localhost'
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

CORS_ALLOW_CREDENTIALS = True

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = DATA_DIR / 'media' if _data_dir else BASE_DIR